# Generated by Django 5.0.4 on 2024-04-18 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_author_image_alter_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_sub',
            new_name='is_child',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='course.category', verbose_name='زیر مجموعه'),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.author', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='courses', to='course.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='file',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='course.course', verbose_name='دوره'),
        ),
    ]
