# Generated by Django 5.0.4 on 2024-04-18 17:01

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=course.models.course_directory_path, verbose_name='تصویر'),
        ),
    ]
