# Generated by Django 5.0.4 on 2024-04-18 17:04

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default='', verbose_name='بایوگرافی'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=course.models.author_directory_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='author',
            name='social_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس فضای مجازی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to=course.models.course_directory_path, verbose_name='تصویر'),
        ),
    ]
